### PR TITLE
Set Rotor multiplier to 2.9

### PR DESCRIPTION
**Pull request by EstebanMz**
Past PR went wrong so I had to repeat it.
This is a suggestion made by Michel, who couldn't give an opinion about the changes that were sent yesterday.

### CODE REVIEW

**Comment by BGMP** [comment]
Shouldn't we at least try the original nerf first?

**Comment by BGMP** [comment]
@EstebanMz should I close this one?

**Comment by EstebanMz** [comment]
Well, I'm not sure, yes, I guess. It's known that Rotor is somehow more competitve than RV Loco, but also we're comparing two of the worst cars overall in the game...

**Review by BGMP — APPROVED** [review]
OK, I think it's time we give this a try.

**Pull request merged**
